class NetworkError extends Error {
  constructor(message) {
    super(message);
    this.name = 'NetworkError';
  }
}

// TODO: 1
const fetchingUserFromInternet = (isOffline) => {
  return new Promise((resolve, reject) => {
  setTimeout(() => {
    if(!isOffline) {
        resolve({ name: 'John', age: 18 });
    } else{
        reject(new NetworkError('Gagal mendapatkan data dari internet'), null);
    }
  }, 500);
  })
};


// TODO: 2
async function gettingUserName(){
  try{
      const fetchingUserData = await fetchingUserFromInternet(false);
      return fetchingUserData.name
  }catch(error){
      if(error instanceof NetworkError){
          return error.message
      }
  }
};


(async () => {
    console.log(await gettingUserName());
})()
